### PR TITLE
Update GeckoView to 98

### LINKED ISSUE #40: Problem building plugin with newer GeckoView Version
Hello everyone,

When bulding the GeckoView plugin with the newest version ("95.0.20211129150630"), several errors occur and it is no longer possible to build the plugin.
The erros are:
grafik

Any help in solving them would be much appreciated!

P.S.: My plan ist to get the plugin running with the newest version of gecko und eventually on arm64.

### PR DESCRIPTION
**Pull request by IanPhilips**
Fixes #40 - For some reason this will no longer build on my Oculus Go, so I can't actually test if the updates work. The changes are minimal though so it should! Any help testing this on an Oculus Quest would be appreciated. 

Also, if anyone has a spare Oculus Quest I'd take it off your hands or buy it for cheap!

### CODE REVIEW

**Comment by alphayama** [comment]
The app works fine on Oculus Quest 2.

**Comment by art3miz18** [comment]
@alphayama can you help me out, i tried it on meta quest 2 it dint work for me... I did update gradle version and oculus module

**Comment by alphayama** [comment]
@art3miz18 I was not able to run it initially as well. I just used the Unity version used by Ian and the Oculus Integration and Gradle versions that came with the project. If I have time, I will try to migrate it to newer Unity, OculusIntegration versions.

**Comment by khelkun** [comment]
@IanPhilips 
Does this really work please? Because [app-debug.arr](https://github.com/IanPhilips/UnityOculusAndroidVRBrowser/blob/master/UnityProject/Assets/Plugin/Android/app-debug.aar) was updated but [geckoview-armeabi-v7a-80.0.20200818235255.aar](https://github.com/IanPhilips/UnityOculusAndroidVRBrowser/blob/master/UnityProject/Assets/Plugin/Android/geckoview-armeabi-v7a-80.0.20200818235255.aar) was not replaced by [geckoview-armeabi-v7a-98.0.20220313140707.aar](https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-armeabi-v7a/98.0.20220313140707/geckoview-armeabi-v7a-98.0.20220313140707.aar)

If  I replace `geckoview-armeabi-v7a-80.0.20200818235255.aar` file by `geckoview-armeabi-v7a-98.0.20220313140707.aar` inside `UnityProject/Assets/Plugin/`, then the Unity app crashes at startup.

**Pull request merged**
